### ISSUE TITLE
Extend ImagingCondition to include the three dimensions for pixelSize

### ISSUE THREAD

**Issue by agbeltran** [CellMigStandOrg/MIACME#11]
MIACME currently includes pixelSize, without distinguishing between the dimensions. Extend it to include pixelSizeX, pixelSizeY, pixelSizeZ and their corresponding units.

(following discussions with @leenvantroys Gert-Jan.Bakker and Merijn vanErp)

**Comment by joshmoore** [comment]
:+1: That certainly matches what's in the OME metadata and what Bio-Formats would read out of a given fileset. See https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#Pixels

**Comment by agbeltran** [comment]
Thanks @joshmoore, that's useful to know and to reference. Can you explain ```SizeC``` and ```SizeT``` and the distinction between sizes and physical sizes? Is it something we should also consider in MIACME? It is interesting to see the list of units in the enum, I gather that you are not tagging units with an ontology?

**Comment by agbeltran** [comment]
According to https://docs.openmicroscopy.org/bio-formats/5.8.2/developers/generating-test-images.html, ```SizeC``` refers to channels, and ```SizeT``` to timepoints as it could have been guessed.

**Comment by sbesson** [comment]
@agbeltran sorry for the delay. Images as currently defined by the OME Model have at least 5 dimensions: three dimensions the space (`X`,`Y`,`Z`), one for the time (`T`) and one for the channels (`C`). 

- `size{X,Y,Z,T,C}` defines the range each image spans alongside each of these dimensions. So for instance a 3-channel time-lapse image would have `sizeT=100` and `sizeC=3`.
- for spatial dimensions, in addition `physicalSize{X,Y,Z}` and the related `physicalSize{X,Y,Z}Unit` will express the scale of individual pixels in physical space i.e. the mapping between the pixel space and the physical space

**Comment by agbeltran** [comment]
Thanks @sbesson - I think it will be useful for MIACME to follow the same structure, so I will extend it in that respect.

**Comment by agbeltran** [comment]
minimum specification: https://docs.openmicroscopy.org/ome-model/5.6.3/specifications/minimum.html

pointed out by @sbesson

**Comment by agbeltran** [comment]
MIACME v1.0 spreadsheet has been updated and the schemas extended with a pixel schema:

https://docs.google.com/spreadsheets/d/1fJouFpBCs2Af8bXm2SUQy1ZJRaQrSgDLPB4mwoQvrek/edit#gid=0

https://github.com/CellMigStandOrg/MIACME/blob/master/v1.0/schemas/pixel_schema.json
